#!/bin/sh
mute="&>/dev/null"
url="http://127.0.0.1/startup.php"

# Show a loading image while X starts
fbi -T 2 --noverbose /var/www/html/resources/splash.jpg &

# Hide mouse after 1s of inactivity
unclutter -idle 1 -root &

while true; do

	fbset -left 300 -right 300;

	# Kill running instances
	killall -9 luakit;
	killall -9 matchbox-window-manager;

	# Disable DPMS / Screen blanking
	xset -dpms
	xset s off

	# Once the browser is running, prep to kill loading image
	(sleep 5; killall -9 fbi) &

	# Start window manager
	matchbox-window-manager -use_titlebar no -use_cursor yes &
	luakit $url

	sleep 1s;
done;
